# Generated by Django 6.0.3 on 2026-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_female_votes_profile_male_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desired_partner_traits',
            field=models.JSONField(blank=True, default=dict, help_text='What the user is looking for'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hidden_data_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of keys in profile to hide from public'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_quiz_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='psychological_profile',
            field=models.JSONField(blank=True, default=dict, help_text='AI generated deep psychological profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='self_reported_traits',
            field=models.JSONField(blank=True, default=dict, help_text="User's answers to the onboarding quiz"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_ai_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken')], default='pending', max_length=20),
        ),
    ]
