# Generated by Django 6.0.3 on 2026-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_desired_partner_traits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='desired_partner_traits',
        ),
        migrations.AddField(
            model_name='profile',
            name='connection_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='What kind of people and conversations the user seeks'),
        ),
        migrations.AddField(
            model_name='profile',
            name='conversation_topics',
            field=models.JSONField(blank=True, default=list, help_text='AI-extracted topics from past conversations'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_intent',
            field=models.TextField(blank=True, help_text='Freeform: what the user wants to talk about right now'),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, help_text='Topics the user has deep knowledge in'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='Topics the user is interested in'),
        ),
    ]
