# Generated by Django 6.0.3 on 2026-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_desired_partner_traits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_status_image_url',
            field=models.URLField(blank=True, help_text='Live AI generated status/warning image during chat', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='persona_image_url',
            field=models.URLField(blank=True, help_text='AI generated conceptual avatar', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=100, help_text='Dynamic AI-adjusted trust score based on chat intent (0-100)'),
        ),
    ]
