# Generated by Django 6.0.3 on 2026-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_chat_status_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token', max_length=255, null=True),
        ),
    ]
