# Generated by Django 6.0.3 on 2026-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="Languages the user speaks, e.g. ['en', 'hi']"),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude for distance-based matching', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude for distance-based matching', null=True),
        ),
    ]
