# Generated by Django 5.2.9 on 2026-03-29 05:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_languages_profile_latitude_profile_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocks_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='calls_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='calls_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='friendships_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_face_in_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_profile_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualifying_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_last_calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_tier',
            field=models.CharField(choices=[('trusted', 'Trusted'), ('established', 'Established'), ('new', 'New'), ('flagged', 'Flagged')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('points_change', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked_user')},
            },
        ),
    ]
