# Generated by Django 6.0.4 on 2026-04-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_blocks_received_profile_calls_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expertise_embedding',
            field=models.JSONField(blank=True, default=list, help_text='Mathematical vector embedding of expertise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_embedding',
            field=models.JSONField(blank=True, default=list, help_text='Mathematical vector embedding of interests'),
        ),
    ]
