# Generated by Django 5.2.9 on 2026-04-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_expertise_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='successful_searches',
            field=models.IntegerField(default=0, help_text='Number of successful live searches yielding potential users'),
        ),
    ]
