# Generated by Django 5.2.9 on 2026-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_successful_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, help_text='High-performance spatial index', max_length=12, null=True),
        ),
    ]
