# Generated by Django 5.2.9 on 2026-04-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_geohash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_provider',
            field=models.CharField(default='email', help_text='The method used for authentication', max_length=50),
        ),
    ]
