# Generated by Django 6.0.4 on 2026-04-13 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_ai_llm_searches',
            field=models.IntegerField(default=0, help_text='Searches hitting the LLM (Limit 4 free, 40 subbed)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_roulette_searches',
            field=models.IntegerField(default=0, help_text='Random matching (Limit 20 free, Unlimited subbed)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_standard_searches',
            field=models.IntegerField(default=0, help_text='Non-LLM searches (e.g. cached intent). (Limit combined 4 free, 100 subbed)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_quota_reset_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when daily quotas were last reset'),
        ),
    ]
