# Generated by Django 6.0.3 on 2026-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_profile_female_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_for_offline_search',
            field=models.BooleanField(default=False, help_text='Allow others to discover this profile when offline (resets daily at 12 PM GMT)'),
        ),
    ]
