# Generated by Django 6.0.3 on 2026-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_available_for_offline_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=60, help_text='Dynamic AI-adjusted trust score based on chat intent (0-100)'),
        ),
    ]
