# Generated by Django 6.0.3 on 2026-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weekly_quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_quiz_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
