version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=glysmork_db
      - POSTGRES_USER=glysmork_user
      - POSTGRES_PASSWORD=glysmork_password
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: .
    command: gunicorn chat.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=postgres://glysmork_user:glysmork_password@db:5432/glysmork_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: always

  onboarding_service:
    build: 
      context: .
      dockerfile: onboarding_service/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
