# Generated by Django 6.0.3 on 2026-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='callee',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='declined',
        ),
        migrations.AddField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('ended', 'Ended'), ('declined', 'Declined'), ('no_answer', 'No Answer'), ('unavailable', 'Unavailable'), ('cancelled', 'Cancelled')], default='ended', max_length=20),
        ),
    ]
