# Generated by Django 6.0.3 on 2026-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_message_deleted_for_everyone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
