# Generated by Django 6.0.3 on 2026-03-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='chat_type',
            field=models.CharField(choices=[('session', 'Discovery Session'), ('friend', 'Friend Chat')], default='friend', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
