# Generated by Django 6.0.3 on 2026-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_message_options_message_status_room_chat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='match_reason',
            field=models.TextField(blank=True, help_text='AI-generated reason why these users were matched.', null=True),
        ),
    ]
