"use client";

import Logo from '@/components/Logo';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen bg-background text-gray-300">
            <div className="max-w-3xl mx-auto px-6 py-12">
                <div className="flex items-center gap-4 mb-12">
                    <Link href="/" className="p-2 rounded-full hover:bg-white/5 transition-colors">
                        <ArrowLeft className="w-5 h-5 text-gray-400" />
                    </Link>
                    <Logo size="md" />
                </div>

                <h1 className="text-4xl font-bold text-white mb-2">Privacy Policy</h1>
                <p className="text-sm text-gray-500 mb-10 font-mono">Last updated: March 5, 2026</p>

                <div className="space-y-8 leading-relaxed text-sm">
                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. What We Collect</h2>
                        <p>Glysmork collects and processes the following types of data to provide our connection matching service:</p>
                        <ul className="list-disc ml-6 mt-3 space-y-2">
                            <li><strong className="text-white">Account Data:</strong> Username, email, age, gender, profile image, and bio.</li>
                            <li><strong className="text-white">Onboarding Quiz Answers:</strong> Your responses to psychological, interest, expertise, and goal-related questions during the analysis quiz.</li>
                            <li><strong className="text-white">AI-Generated Profile:</strong> Psychological traits, attachment style, communication patterns, interests, and expertise areas generated by our AI analysis of your quiz answers.</li>
                            <li><strong className="text-white">Conversation Data:</strong> Messages sent and received in chat rooms are stored on our servers. We use AI to analyze conversations to extract interests, topics discussed, and behavioral patterns to improve your connection matches.</li>
                            <li><strong className="text-white">Intent Queries:</strong> The freeform search queries you submit when looking for connections.</li>
                            <li><strong className="text-white">Usage Data:</strong> Login timestamps, session data, and interaction patterns.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. How We Use Your Data</h2>
                        <ul className="list-disc ml-6 space-y-2">
                            <li><strong className="text-white">Connection Matching:</strong> Your profile data (psychology, interests, expertise, conversation patterns) is used by our AI to find the best possible matches for your intent queries.</li>
                            <li><strong className="text-white">Passive Conversation Analysis:</strong> Messages are periodically analyzed by AI to extract new interests, expertise areas, and conversation topics. This data enriches your profile and improves future matches.</li>
                            <li><strong className="text-white">Improvement Bot:</strong> When you use the AI coaching feature, your profile data is used to provide personalized advice.</li>
                            <li><strong className="text-white">Safety & Moderation:</strong> Messages and accounts may be reviewed by our moderation team if reported by other users.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">3. Your Privacy Controls</h2>
                        <p>You have granular control over your data visibility:</p>
                        <ul className="list-disc ml-6 mt-3 space-y-2">
                            <li>Toggle your profile between public and private.</li>
                            <li>Choose whether your AI analysis is visible to matched connections.</li>
                            <li>Selectively hide specific data fields (interests, expertise, psychology, conversation topics, location) from other users.</li>
                            <li>Delete messages for yourself or for everyone.</li>
                            <li>Download a full transcript of any conversation you participate in.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. Data Storage & Retention</h2>
                        <ul className="list-disc ml-6 space-y-2">
                            <li>Your data is stored on our secure servers.</li>
                            <li>Messages are retained indefinitely unless deleted by users. Messages "deleted for everyone" are marked as deleted but may be retained in our backend for moderation purposes.</li>
                            <li>Reported accounts and their associated data are preserved for review by our moderation team.</li>
                            <li>Transcripts are generated on-demand and not stored separately.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. Third-Party Services</h2>
                        <p>We use <strong className="text-white">Google Gemini AI</strong> to analyze quiz responses, match intent queries, analyze conversations, and power the Improvement Bot. Your data is sent to Google&apos;s API for processing. Please refer to <a href="https://policies.google.com/privacy" className="text-purple-400 hover:text-purple-300 underline" target="_blank" rel="noopener noreferrer">Google&apos;s Privacy Policy</a> for details on how they handle data.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">6. Your Rights</h2>
                        <ul className="list-disc ml-6 space-y-2">
                            <li>You can request a copy of all data we hold about you.</li>
                            <li>You can request deletion of your account and associated data.</li>
                            <li>You can update your privacy settings at any time from the dashboard.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">7. Contact</h2>
                        <p>For privacy-related inquiries, contact us at <span className="text-purple-400">privacy@glysmork.com</span>.</p>
                    </section>
                </div>

                <div className="mt-16 pt-8 border-t border-white/10 text-center">
                    <Link href="/terms" className="text-purple-400 hover:text-purple-300 text-sm">Terms of Service</Link>
                    <span className="text-gray-600 mx-3">•</span>
                    <Link href="/" className="text-gray-500 hover:text-gray-400 text-sm">Back to Home</Link>
                </div>
            </div>
        </div>
    );
}
