# Generated by Django 6.0.3 on 2026-03-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_alter_callrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='loop',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
