# Generated by Django 6.0.3 on 2026-03-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_offlinesearch_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesearch',
            name='country_filter',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='offlinesearch',
            name='distance_km_filter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlinesearch',
            name='language_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
