# Generated by Django 6.0.3 on 2026-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_offlinesearch_country_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinesearch',
            name='country_filter',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='offlinesearch',
            name='language_filter',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
