# Generated by Django 5.2.9 on 2026-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GemPackage',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
